
name: make_google_vm
on:
  workflow_dispatch:

jobs:
  provision_vm:
    runs-on: ubuntu-latest
    
    env:
      # these need to be updated to suit the configuration
      WORKLOAD_ID_PROVIDER: 'projects/258329370240/locations/global/workloadIdentityPools/github-pool-05/providers/github-token-provider-05'
      PROJECT_ID: birkbeck-ccp-01
      TF_VAR_project_id: birkbeck-ccp-01
      SERVICE_ACCOUNT_NAME: my-github-05

    permissions:
      contents: read
      id-token: write

    steps:
    - id: checkout
      uses: actions/checkout@v3
    
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: '${{ env.WORKLOAD_ID_PROVIDER }}'
        service_account: '${{ env.SERVICE_ACCOUNT_NAME }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

    - name: 'terraform-vm'
      run: |-
        cd terraform
        terraform fmt -check
        terraform init
        terraform apply -input=false -auto-approve
