
name: make_google_vm
on:
  workflow_dispatch:

jobs:
  provision_vm:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - id: checkout
      uses: actions/checkout@v3
    
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/258329370240/locations/global/workloadIdentityPools/mpette200-github-01/providers/github-actions'
        service_account: 'mpette200-github@birkbeck-ccp-01.iam.gserviceaccount.com'

    - name: Login gcloud
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

    - name: 'Use gcloud CLI'
      run: |-
        gcloud info
